services:
  # ========================================
  # APPLICATION OHKAY SERVER
  # ========================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ohkay-server
    restart: unless-stopped
    ports:
      - "8100:8100"
    environment:
      - NODE_ENV=production
      - PORT=8100
      
      # Auth Database
      - AUTH_DB_HOST=postgres
      - AUTH_DB_PORT=5432
      - AUTH_DB_NAME=ohkay_auth
      
      # DM Database
      - DM_DB_HOST=postgres
      - DM_DB_PORT=5432
      - DM_DB_NAME=ohkay_dms
      
      # Registry Database
      - REGISTRY_DB_HOST=postgres
      - REGISTRY_DB_PORT=5432
      - REGISTRY_DB_NAME=ohkay_server_registry
      
      # Database Credentials (shared)
      - DB_USER=${DB_USER:-ohkay_user}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Database Admin Credentials (pour création dynamique de DB)
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASSWORD=${POSTGRES_PASSWORD:-${DB_PASSWORD}}
      
      # Security
      - JWT_SECRET=${JWT_SECRET}
      - INSTANCE_PASSWORD=${INSTANCE_PASSWORD}
      - DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY:-change-me-in-production}
      - MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY:-change-me-in-production}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # CORS
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ohkay-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ========================================
  # POSTGRESQL UNIQUE - Toutes les bases de données
  # ========================================
  postgres:
    image: postgres:16-alpine
    container_name: ohkay-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-${DB_PASSWORD}}
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Exposé pour debug (optionnel)
    networks:
      - ohkay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"

networks:
  ohkay-network:
    driver: bridge

volumes:
  postgres-data:
